spring:
  application:
    name: admin-client


eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  endpoint:
    health:
      show-details: always


  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8762